In [1]:
import pandas as pd
import numpy as np

In [2]:
train_str = 'Data/data_Sven_long.csv'
#labels_str = 'train_labels.csv'
df_train = pd.read_csv(train_str)
#df_labels_unsorted = pd.read_csv(labels_str)

In [3]:
pd.set_option('display.max_rows', 30)
pd.set_option('display.max_columns', None)

In [8]:
df_train = df_train.drop(columns='Time')
df_train

,pid,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,RRate,Fibrinogen,Phosphate,WBC,Creatinine,PaCO2,AST,FiO2,Platelets,SaO2,Glucose,ABPm,Magnesium,Potassium,ABPd,Calcium,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,1,34.0,32.893,38.657,12.0,2.349,36.0,8.700,24.000,-2.000,16.00,273.38,4.600,6.3,0.50,45.000,158.23,0.500,143.0,93.271,120.0,84.000,1.20,3.800,61.000,7.6,96.624,100.0,1.172,114.000,24.60,94.0,1.544,6.452,142.000,7.330
1,1,34.0,32.893,38.657,12.0,2.349,36.0,8.675,24.250,-2.000,16.00,273.38,4.600,6.1,0.50,44.000,158.23,0.500,143.0,93.271,120.0,81.000,1.35,3.837,62.500,7.6,96.624,100.0,1.172,113.625,24.05,99.0,1.544,6.452,125.000,7.330
2,1,34.0,32.893,38.657,12.0,2.349,36.0,8.650,24.500,0.000,18.00,273.38,4.600,5.9,0.50,43.000,158.23,0.400,143.0,93.271,120.0,74.000,1.50,3.875,59.000,7.6,96.624,100.0,1.172,113.250,23.50,92.0,1.544,6.452,110.000,7.370
3,1,34.0,32.893,38.657,12.0,2.349,37.0,8.625,24.750,0.000,18.00,273.38,4.600,5.7,0.50,42.857,158.23,0.400,143.0,93.271,120.0,66.000,1.65,3.912,49.500,7.6,96.624,100.0,1.172,112.875,22.95,88.0,1.544,6.452,104.000,7.370
4,1,34.0,32.893,38.657,12.0,2.349,37.0,8.600,25.000,0.000,18.00,273.38,4.600,5.5,0.50,42.714,158.23,0.400,143.0,93.271,120.0,63.000,1.80,3.950,48.000,7.6,96.624,100.0,1.172,112.500,22.40,81.0,1.544,6.452,100.000,7.410
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227935,31658,60.0,32.893,38.657,13.0,2.349,37.0,14.400,23.806,-0.762,18.12,273.38,3.617,4.6,0.71,40.822,158.23,0.658,164.0,93.271,104.0,91.000,1.90,3.600,70.000,8.8,96.624,96.0,1.172,105.922,40.20,71.0,1.544,6.452,127.000,7.377
227936,31658,60.0,32.893,38.657,13.0,2.349,37.0,14.400,23.806,-0.762,18.12,273.38,3.617,4.6,0.71,40.822,158.23,0.658,164.0,93.271,106.0,96.667,1.90,3.600,73.667,8.8,96.624,96.0,1.172,105.922,40.20,71.0,1.544,6.452,129.667,7.377
227937,31658,60.0,32.893,38.657,13.0,2.349,37.0,14.400,23.806,-0.762,18.12,273.38,3.617,4.6,0.71,40.822,158.23,0.658,164.0,93.271,108.0,102.333,1.90,3.600,77.333,8.8,96.624,96.0,1.172,105.922,40.20,71.0,1.544,6.452,132.333,7.377
227938,31658,60.0,32.893,38.657,13.0,2.349,37.0,14.400,23.806,-0.762,18.12,273.38,3.617,4.6,0.71,40.822,158.23,0.658,164.0,93.271,110.0,108.000,1.90,3.600,81.000,8.8,96.624,96.0,1.172,105.922,40.20,71.0,1.544,6.452,135.000,7.377
227939,31658,60.0,32.893,38.657,13.0,2.349,37.0,14.400,23.806,-0.762,18.12,273.38,3.617,4.6,0.71,40.822,158.23,0.658,164.0,93.271,110.0,108.000,1.90,3.600,81.000,8.8,96.624,96.0,1.172,105.922,40.20,71.0,1.544,6.452,135.000,7.377

In [9]:
new_shape = (df_train.shape[0]//12,df_train.shape[1])
new_shape

(18995, 36)

In [10]:
np_train = np.empty((new_shape))
df_train = df_train.copy()

for i in range(len(df_train.pid.unique())):
    mask = df_train.loc[:,'pid'] == df_train.pid.unique()[i]
    np_train[i,:] = df_train[mask].mean()
    
df_train_short = pd.DataFrame(np_train, columns=df_train.columns)
df_train_short

,pid,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,RRate,Fibrinogen,Phosphate,WBC,Creatinine,PaCO2,AST,FiO2,Platelets,SaO2,Glucose,ABPm,Magnesium,Potassium,ABPd,Calcium,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,1.0,34.0,32.893,38.657,12.000000,2.349000,37.041667,8.575000,25.250000,-0.333333,17.000000,273.38,4.600000,5.300000,0.500000,42.750000,158.23,0.416667,143.000000,93.271000,120.000000,68.333333,1.800000,3.987333,50.250000,7.600000,96.624,100.000000,1.172,112.125,23.241667,77.083333,1.544,6.452,114.500000,7.381667
1,2.0,86.0,32.893,31.800,32.000000,2.349000,36.000000,13.100000,23.806000,-0.762000,18.500000,273.38,3.800000,9.300000,2.120000,40.822000,158.23,0.658000,226.000000,93.271000,117.666667,95.583333,2.100000,3.800000,70.666667,9.500000,96.624,96.000000,1.172,105.922,40.200000,59.000000,1.544,0.440,132.583333,7.377000
2,4.0,66.0,32.893,34.600,8.000000,2.349000,36.541667,10.475000,23.806000,-0.762000,14.000000,273.38,3.100000,7.683333,0.543333,40.822000,34.00,0.658000,267.333333,93.271000,103.979167,80.333333,2.504167,3.533333,50.583333,8.166667,130.000,99.333333,0.100,105.922,33.291667,72.166667,0.600,0.020,127.166667,7.377000
3,6.0,66.0,32.893,53.800,32.000000,1.800000,37.166667,10.408333,19.250000,-2.833333,15.833333,273.38,3.100000,39.700000,1.375000,39.625000,158.23,0.529167,105.000000,93.708333,114.541667,65.750000,3.100000,4.587500,48.833333,7.800000,96.624,99.333333,1.172,112.250,30.500000,87.333333,1.544,6.452,100.666667,7.348333
4,8.0,42.0,32.893,38.657,18.000000,2.349000,36.000000,10.754000,23.806000,-0.762000,17.166667,273.38,3.300000,11.567000,6.460000,40.822000,158.23,0.658000,210.727000,93.271000,118.000000,142.750000,2.100000,4.300000,108.833333,7.900000,96.624,97.666667,1.172,105.922,32.022000,80.833333,1.544,0.080,205.833333,7.377000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18990,31653.0,52.0,32.893,25.800,11.000000,1.633333,36.000000,9.600000,22.583333,0.000000,15.500000,633.00,4.400000,17.141667,0.700000,49.000000,158.23,0.658000,489.000000,93.271000,137.000000,66.250000,2.150000,4.858333,48.125000,7.900000,96.624,96.333333,1.172,106.000,31.362500,107.750000,1.544,6.452,86.583333,7.330000
18991,31654.0,66.0,32.893,38.657,32.666667,2.349000,37.458333,11.200000,23.806000,-0.762000,16.666667,273.38,5.366667,2.000000,10.313333,40.822000,158.23,0.658000,124.000000,93.271000,94.666667,122.750000,2.100000,5.666667,94.458333,8.533333,96.624,95.916667,1.172,105.922,34.600000,91.500000,1.544,6.452,165.083333,7.377000
18992,31656.0,44.0,32.893,38.657,15.000000,2.349000,38.000000,12.400000,24.000000,-3.125000,24.583333,273.38,3.617000,24.000000,0.700000,45.333333,158.23,0.400000,345.000000,93.271000,115.000000,80.000000,1.996000,4.000000,65.166667,7.742000,96.624,100.000000,1.172,97.000,36.700000,99.416667,1.544,6.452,101.750000,7.306667
18993,31657.0,70.0,32.893,38.657,23.001000,2.349000,36.458333,10.754000,23.806000,-0.762000,15.000000,273.38,3.617000,11.567000,1.470000,40.822000,158.23,0.658000,210.727000,93.271000,138.977000,73.708333,1.996000,4.115000,63.041667,7.742000,96.624,99.125000,1.172,105.922,32.022000,64.250000,1.544,6.452,111.041667,7.377000
18994,31658.0,60.0,32.893,38.657,13.000000,2.349000,36.583333,14.400000,23.806000,-0.762000,18.120000,273.38,3.617000,4.600000,0.710000,40.822000,158.23,0.658000,164.000000,93.271000,102.500000,95.250000,1.900000,3.600000,73.583333,8.800000,96.624,96.000000,1.172,105.922,40.200000,67.250000,1.544,6.452,133.166667,7.377000

In [17]:
df_train_short = df_train_short.astype({'pid':'int32'})
df_train_short = df_train_short.astype({'Age':'int32'})
df_train_short.to_csv('Data/data_Sven_short.csv', index=False, float_format='%.3f')